name: goodshit
favicon: null
layout_spectrum: 0.5680746228899807
typography_spectrum: 0.5583596008364111
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8808060833252966
  lightness: 0.9837383946869522
  saturation: 0.019358663354068995
  rhythmicContrast: 0.8229395383968949
purpose: []
